# Omarchy-style Hyprlock for normal Hyprland

$font = JetBrainsMono Nerd Font Mono

$color = rgba(0, 0, 0, 0.20)
$inner_color = rgba(18, 18, 18, 0.68)
$outer_color = rgba(242, 244, 248, 0.42)
$font_color = rgba(242, 244, 248, 0.98)
$check_color = rgba(242, 244, 248, 0.95)

general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = /home/xacce/Pictures/wallhaven-6dm2r6_2560x1440.png
    blur_passes = 1
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 350, 50
    position = 0, -10
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 1

    font_family = $font
    font_color = $font_color
    placeholder_text = unlock

    check_color = $check_color
    fail_text = $FAIL ($ATTEMPTS)

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}
