Net/ThemeName "Graphite-blue-Dark-compact"
Net/IconThemeName "Papirus-Dark"
Gtk/CursorThemeName "Bibata-Original-Classic"
Gtk/FontName "JetBrainsMono Nerd Font Mono 10"
Net/EnableEventSounds 0
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 0
Xft/HintStyle "hintnone"
Xft/RGBA "rgb"
