# -----------------------------------------------------
# General window decoration
# -----------------------------------------------------

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    col.active_border = rgba(f2f4f8ff)
    col.inactive_border = rgba(4a4a4aaa)
    layout = dwindle
}
layerrule = match:namespace waybar, blur on

windowrule = match:title ^(Picture-in-Picture)$, float on
windowrule = match:title ^(Picture-in-Picture)$, pin on
windowrule = match:title ^(Picture-in-Picture)$, size 480 270
windowrule = match:title ^(Picture-in-Picture)$, move 100%-500 40

windowrule = match:title ^(Open File)(.*)$, float on
windowrule = match:title ^(Save File)(.*)$, float on
windowrule = match:title ^(Choose File)(.*)$, float on
windowrule = match:title ^(Authentication Required)(.*)$, float on
windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(pavucontrol)$, size 900 560
windowrule = match:class ^(pavucontrol)$, center 1
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(nm-connection-editor)$, center 1
windowrule = match:class ^(nm-connection-editor)$, size 960 680
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueman-manager)$, center 1
windowrule = match:class ^(blueman-manager)$, size 980 700
windowrule = match:title ^(Open Folder)(.*)$, float on
windowrule = match:title ^(Confirm to replace files)(.*)$, float on
